### ISSUE TITLE
V 1.0.5.8 Grid layout is being destroyed on refresh 

### ISSUE THREAD

**Issue by san-86** [mehrgithub/dcrmeg#12] opened 2017-06-12 12:10 UTC
We have a case where we have 2 sections open in the grid, and when we refresh the lowest opened grid section it repeats the content of that grid section in the one above everytime we refresh not just once, it happens en both IE and Chrome 

 I have attached a picture that shows it, Hope its easy to fix.. 

 Thank you for your great work.
![layouterror](https://user-images.githubusercontent.com/29374830/27033213-ace0e9d2-4f78-11e7-9c3d-5f6b4ed1fc5c.PNG)

**Comment by mehrgithub** [comment] 2017-06-13 09:53
Thank you for reporting this bug. I will try to include a fix for this issue in the next release. Seems to be a indexing mismatch with the internal structures.

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-06-13 11:47
Looking forward to the new release :-), Thank you for your great work and fast response times.

**Comment by mehrgithub** [comment] 2017-06-16 15:05
Hi,

Please download the new version and let me know if the issue is resolved.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-06-16 15:59
my current grids stands still with loading icon and write 
SCRIPT5007: Unable to get property 'Label' of undefined or null reference 
is this due to a bug in the new version or do I need to change something in the grid for it to work ?
Or will it only work for new grids ?

**Comment by san-86** [comment] 2017-06-16 16:05
![1059error](https://user-images.githubusercontent.com/29374830/27234745-617374a8-52be-11e7-8293-5de828f34a8e.PNG)

**Comment by mehrgithub** [comment] 2017-06-16 16:55
I did test the new release on multiple environments (2013, 2015, 365) using IE 11, Chrome, and FF and didn't get any errors. There should be no need to change anything in the grid and the solution should be backward compatible with previous versions. However I could have overlooked something.

Questions to help me find the cause, mainly where in the code the error is originating (hope you don't mind):

1. What version of CRM are you using?
2. Do you see any part of the grid or just the loading icon?
3. Does the grid configuration loads without issues?
4. If you change something in the grid configuration and save, does the error persists?
5. Are you using the managed or unmanaged solution? The managed solution uses minified versions of the JS files.
6. If you don't mind using Chrome, from the console, it allows you to navigate to the line where the error occurred. It also displays a mini call stack as well. Or you can turn on the switch in IE to break if a script error occurs which takes you to the source line where the error is.
7. Would you be able to post a snapshot of the grid configuration for one of the grids that is causing the error?

Thank you,
Mehrdad

**Comment by mehrgithub** [comment] 2017-06-16 17:05
One thing I forgot to ask, are you using any of the JS callbacks?

If yes, could you please deactivate the JS callbacks and try? I believe the problem is with the DCrmEgGridOnBeforeFetchRecords JS callback.

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-06-16 18:17
I am using the JS callbacks, so I will try to deactivate them and see if that is it :-)

**Comment by san-86** [comment] 2017-06-16 18:27
after I have deactivated all the callbacks, some of the grid is shown but now it looks very different and it can't show the related entities, it shows the error "Creating a child grid failed. 'cas' is undefined" in the console

**Comment by san-86** [comment] 2017-06-16 18:30
<img width="713" alt="griderror" src="https://user-images.githubusercontent.com/29374830/27239773-9293e75c-52d2-11e7-9fd6-75f33f752ae7.PNG">

**Comment by san-86** [comment] 2017-06-16 18:32
it also still says , Status Code: 404, Function: RetrieveVersion Not Found in the console

**Comment by san-86** [comment] 2017-06-16 18:46
I'm on a CRM 2013 On Premise, the configuration page loads without problems, I have tried to make a change to the configuration and save, but the problem persists, I'm Using the managed solution

here is a picture of the Chrome console : 
<img width="703" alt="chromeconsole" src="https://user-images.githubusercontent.com/29374830/27240426-e0059e48-52d4-11e7-9e5c-5ae63c491de9.PNG">

**Comment by mehrgithub** [comment] 2017-06-16 18:56
"Status Code: 404, Function: RetrieveVersion Not Found in the console" is by design and not an actual error. This is part of Web API addition to detect if the current running CRM supports Web API (2016, 365). If not, the grid will use soap end points. You should see the same call when loading the grid configuration.

I also did confirm that the "DCrmEgGridOnBeforeFetchRecords" JS callback was the cause of the previous error.

I did find the new bug you reported "cas" is undefined. I am testing a fix for it and will upload a new release shortly.

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-06-16 19:01
Okay, Great to hear that you found the cause of the errors and are able to fix it :-) , will the JS callback also work with your next release ? or will all other js callback work but not "DCrmEgGridOnBeforeFetchRecords"

Thank you for fast feedback :-)

**Comment by mehrgithub** [comment] 2017-06-16 19:18
Please download and import the new release v1.0.6.0. This fixes both issues reported by you. Everything should work (including JS callbacks) without making any changes to the grid.

https://github.com/mehrgithub/dcrmeg/releases

Please let me know.

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-06-16 19:34
I've installed the new version, and the related entities are shown but the grid does not fit the window, so you have to scroll to the right to see all the fields, is this by design or is it a new setup feature , where I have to do something in the configuration ?

**Comment by mehrgithub** [comment] 2017-06-16 20:34
This is by design. In the past there were issues raised regarding display of many columns in a limited space. The columns tend to squash together, making editing difficult to impossible.

When I was adding the sticky header and footer functionality, I decided to remedy this issue by introducing a minimum width for the headers (100 px).

I can always add an option in the configuration to allow setting the minimum width for the grid headers or an option to override the minimum width. Thoughts, suggestions?

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-06-16 21:44
Okay , it's a problem when i can't see all the fields or that it at least use all the space on the screen, a Solution could be as you Said an option to set the minimum width, but would it be possible to make it scale the width by the window while still being able to set min width on the headers ? This Way the important headers would be shown if the window Got smaller , I would still like to be able to decide the width of each header while using the full width of the screen, thoughts ? 
Thank you

**Comment by san-86** [comment] 2017-06-19 06:47
I have been thinking about a solution this weekend, I think either a possibility for disabling your 100px min width so it can look like before the update or a solution where the grid uses the full width of the window and then the fields can be set proportional with %. but as it is now I can't really use it since all the implemetations I have is showing a lot of columns, the scrolling and layout where it only fills half the screen will annoy the users too much ;-). 

I hope this is possible.

Thank you for a great grid :-)

**Comment by san-86** [comment] 2017-06-19 11:47
After a little use of the new version I can see that the Height of the grid also doesn't use the full height of the window, I don't know if this is also something that has come with the latest update ;-), It would also be really great if this wasn't a fixed size so it would follow the window and the screens resolution.

**Comment by mehrgithub** [comment] 2017-06-19 13:28
I will have a new release in the next few days to hopefully correct the resizing issues:

1. Add an option to the configuration to set the minimum width of the columns. Default 15 px.
2. Resize the grid when the size of the container window changes.
3. If a column width is specified in the configuration, it will be used as long as it is not less than the minimum column width specified in the configuration.

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-06-19 13:48
That sounds great, I will be looking forward to tryout the new release :-) 

Thank you for your great work.

**Comment by mehrgithub** [comment] 2017-06-24 11:28
Hi,

Please download the new release and let me know. 

Note:
Prior to 2015, CRM was setting web resources height and width to 100% allowing the host iframe to resize when the browser was resized. However after 2013, the height and width of the iframe is set in pixels and are static. I was able to by pass the width (hack) for the iframe and set it 100%, but not the height of the iframe.

https://github.com/mehrgithub/dcrmeg/releases

I will be closing this issue. If there are any other issues, please open a new one.

Thank you,
Mehrdad

**Closed by mehrgithub** 2017-06-24 11:28 UTC
Labels: bug
