### ISSUE TITLE
Is it possible to change Text alignment in cells?

### ISSUE THREAD

**Issue by san-86** [mehrgithub/dcrmeg#32] opened 2017-07-05 13:27 UTC
I have tried to set the "text-align: center;" in CSS field in the Configuration Entity on Cell level, but nothing happens.  Is it me that is doing it wrong or is it by design ? 

my grid version is 1.0.6.3

Thanks again for this great grid :-)

**Comment by mehrgithub** [comment] 2017-07-05 22:25
It is by design. If no conditions are set then the CSS isn't applied.

However, this is not correct. I will fix the logic to apply the background color, text color, and CSS if there aren't any conditions and any of the mentioned properties have been set.

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-07-06 06:55
Sounds great :-) Thank you

**Comment by mehrgithub** [comment] 2017-07-06 11:16
Hi,

Please download and import the new release v1.0.6.4.

https://github.com/mehrgithub/dcrmeg/releases

I am closing this issue. Please let me know if the issue hasn't been resolved so I can re open the issue.

Thank you,
Mehrdad

**Closed by mehrgithub** 2017-07-06 11:16 UTC
Labels: bug
