### ISSUE TITLE
1.0.6.1 A lot of Blank Space is added when using nested Records

### ISSUE THREAD

**Issue by san-86** [mehrgithub/dcrmeg#23] opened 2017-06-26 07:19 UTC
When using nested records, for every record that is expanded the grid ads a lot of extra white space. 

see attachment :-) 
![gridextraspace](https://user-images.githubusercontent.com/29374830/27528376-73e5c732-5a50-11e7-9bc1-ae3d60f8808d.PNG)

**Comment by san-86** [comment] 2017-06-27 07:14
CRM 2013 , Internet Explorer, Edge And Chrome all shows same behaviour

**Comment by mehrgithub** [comment] 2017-07-01 13:25
Hi,

Please see the new release and let me know if the issue is resolved.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-07-04 09:12
The blank space is gone but the visible space is now very small, I don't know if its possible to make a dynamic refit each time a new child entity is uncollapsed  ?

Thank you for this great grid.
![small viewing area](https://user-images.githubusercontent.com/29374830/27823500-9d018944-60a9-11e7-82be-a1762836e054.PNG)

**Comment by mehrgithub** [comment] 2017-07-04 09:26
It is possible to dynamically resize the sub grid based on the number of records available and the number of records that we are allowed to display. However, the logic will take sometime to implement and test. I will try to add this in the future releases.

However, for the next release (v1.0.6.3), I can add an option to configuration to allow you to set the subgrid body height. Currently, the height of the grid body is set to 80 pixels. Please let me know.

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-07-04 09:35
That would be great as a start to be able to set subgrid height thank you :-)

**Comment by mehrgithub** [comment] 2017-07-05 12:14
Added subgrid tbody height option to v1.0.6.3. Closing this issue. I will let you know when the proper resizing has been added.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad

**Closed by mehrgithub** 2017-07-05 12:14 UTC
Labels: bug

**Comment by san-86** [comment] 2017-07-05 12:19
Thank you :-)
