### ISSUE TITLE
Max header column count is 27

### ISSUE THREAD

**Issue by san-86** [mehrgithub/dcrmeg#13] opened 2017-06-12 13:20 UTC
I just ran into a bump where we could only add 27 coulmns to the grid, no error message is shown, and the field is in the list, but the chosen field is just not added to the column header configuration grid, where you can rearrange the column headers and so on. this by design or a bug ?   

Thank you for your great work.

**Comment by mehrgithub** [comment] 2017-06-13 10:58
Thank you for reporting this bug. The issue is with the CRM field where I am storing the selected fields information. It is of type text with max length of 4000 which is not enough to store more than 27-37 fields information (the variant is due to various field types and the amount of information needed to store for each field).

The name of the field causing the issue on the configuration form, 'dcrmeg_fromentityfieldsattrhidden'

I will try to include a fix for this bug in the next release. Need to replace this field with a multi line text with higher max length of 4000.

Thank you,
Mehrdad

**Comment by san-86** [comment] 2017-06-13 11:54
Thank you for the fast response, I will be looking forward to the new release :-)

**Closed** 2017-06-19 14:10 UTC
Labels: bug
